# Example GitHub Actions YAML config file
name: Run UT Suite

on:
  push:
    # We run whenever a push is made to master (production) or dev (testing) branches
    branches: [ "master", "dev" ]
  pull_request:
    # Only run tests when merging to production code
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # By default, google test libraries aren't installed on the 'ubuntu-latest' image
    # Luckily, they are distributed using apt. Install them as a prerequisite step
    - name: Install Google Test
      run: sudo apt-get update && sudo apt-get install -y libgtest-dev gcovr
    # Generate platform-specific Makefile in subdirectory named 'build'
    - name: cmake
      run: cmake -D CMAKE_BUILD_TYPE=Debug -B build
    # Compile the program and its test binary. Make sure to change working directory to 'build'
    - name: make check
      working-directory: ./build
      run: make check
